---
- name: Nginx installation
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Checking status
      delegate_to: localhost
      become: no
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}"
        status_code: 200
